### ISSUE TITLE
Build fails (/src/9lives.cpp needs removing)

### ISSUE THREAD

**Issue by SteveRussell33** [firolightfog/Yolow#6]
g++ -o plugin.dll build/src/9lives.cpp.o build/src/ChSel2.cpp.o build/src/ChSel6.cpp.o build/src/ChSel8.cpp.o build/src/Euclk.cpp.o build/src/MKnob.cpp.o build/src/PolyCopy10.cpp.o build/src/PolyCopy16.cpp.o build/src/PolyExp10.cpp.o build/src/RandVolt10.cpp.o build/src/SeqP16.cpp.o build/src/SeqP5.cpp.o build/src/Slide16.cpp.o build/src/Slide6.cpp.o build/src/TrigPrec2.cpp.o build/src/TrigPrec6.cpp.o build/src/Xxx.cpp.o build/src/nineLives.cpp.o build/src/plugin.cpp.o build/src/tHex.cpp.o build/src/tXOr.cpp.o -shared -L../.. -lRack -static-libstdc++
C:/msys64/mingw64/bin/../lib/gcc/x86_64-w64-mingw32/11.2.0/../../../../x86_64-w64-mingw32/bin/ld.exe: build/src/nineLives.cpp.o:C:\_Projects\VCVRack\Rack-SDK-2\plugins\Yolow/src/nineLives.cpp:356: multiple definition of `modelnineLives'; build/src/9lives.cpp.o:C:\_Projects\VCVRack\Rack-SDK-2\plugins\Yolow/src/9lives.cpp:356: first defined here
collect2.exe: error: ld returned 1 exit status
make: *** [../../compile.mk:62: plugin.dll] Error 1

**Comment by firolightfog** [comment]
Thanks for the heads-up, Steve! I'm still learning GitHub so any note is much appreciated. Cheers, Andras

**Comment by SteveRussell33** [comment]
I see from one of your latest commits that you've deleated this file. That's good as the build system points out duplicates and will then not produce a `.vcvplugin` file.

Like what you're doing and good luck. I'll close this issue now,
